server.port=8080
spring.application.name=pedidos-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/1b185538-3c99-4453-8c77-b86e78fa3157/v2.0

management.endpoints.web.exposure.include=health

# --- Base de datos local (Postgres via Docker) ---
# Cuando pases a RDS para EP2, solo cambia estas 3 lineas.
spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos360
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Conexión RabbitMQ ---
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
spring.rabbitmq.listener.simple.acknowledge-mode=manual

# --- Topología centralizada (pedidos) ---
app.rabbitmq.exchanges.pedidos=pedidos.exchange
app.rabbitmq.exchanges.dlx=pedidos.dlx

app.rabbitmq.queues.notificaciones=pedidos.notificaciones.queue
app.rabbitmq.queues.ticket-cocina=pedidos.ticket-cocina.queue

app.rabbitmq.dlq.notificaciones=pedidos.notificaciones.queue.dlq
app.rabbitmq.dlq.ticket-cocina=pedidos.ticket-cocina.queue.dlq

app.rabbitmq.routing-keys.pedido-creado=pedido.creado
app.rabbitmq.routing-keys.pedido-estado-cambiado=pedido.estado.cambiado
app.rabbitmq.routing-keys.binding-notificaciones=pedido.#
app.rabbitmq.routing-keys.binding-ticket-cocina=pedido.creado

app.rabbitmq.retry.max-intentos=3
app.rabbitmq.retry.backoff-ms=2000

# Si es true, un listener consume las DLQ y las registra (las saca de la cola).
# Dejalo en false para poder ver los mensajes en la DLQ durante la demo.
app.dlq-logger.enabled=false