server.port=8082
spring.application.name=rabbit-admin-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/1b185538-3c99-4453-8c77-b86e78fa3157/v2.0

management.endpoints.web.exposure.include=health

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# Topología del sistema: no se puede crear/borrar/bindear desde la API
app.rabbit-admin.protegidos=pedidos.exchange,pedidos.dlx,pedidos.notificaciones.queue,pedidos.notificaciones.queue.dlq,pedidos.ticket-cocina.queue,pedidos.ticket-cocina.queue.dlq,ventas.exchange,ventas.dlx,ventas.alertas-stock.queue,ventas.alertas-stock.queue.dlq,ventas.comprobantes.queue,ventas.comprobantes.queue.dlq