server.port=8080
spring.application.name=pedidos-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/1b185538-3c99-4453-8c77-b86e78fa3157/v2.0

management.endpoints.web.exposure.include=health

# --- Base de datos local (Postgres via Docker) ---
# Cuando pases a RDS para EP2, solo cambia estas 3 lineas.
spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos360
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true