server.port=8080
spring.application.name=pedidos-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/1b185538-3c99-4453-8c77-b86e78fa3157/v2.0
management.endpoints.web.exposure.include=health